export enum DcIcons {
  DcIconArrowUp = "dcIcon-arrow-up",
  DcIconCloseCircle = "dcIcon-close-circle",
  DcIconContact = "dcIcon-contact",
  DcIconGlobe = "dcIcon-globe",
  DcIconHelpOutline = "dcIcon-help-outline",
  DcIconHelp = "dcIcon-help",
  DcIconLight = "dcIcon-light",
  DcIconLoading = "dcIcon-loading",
  DcIconMoonOutline = "dcIcon-moon-outline",
  DcIconMoonSharp = "dcIcon-moon-sharp",
  DcIconSettings = "dcIcon-settings",
  DcIconSmile = "dcIcon-smile",
  DcIconVirtualRealityGlasses = "dcIcon-virtual-reality-glasses",
}
